### ISSUE TITLE
parse_datetime should support "@" syntax

### ISSUE THREAD

**Issue by philolo1** [uutils/parse_datetime#30]
We would like parse_time to support "@" syntax, that indicates the seconds passed from the "Thu Jan  1 00:00:00 UTC 1970". 

See related issue: https://github.com/uutils/coreutils/issues/5177

I am intending on working on this issue.

**Comment by Benjscho** [comment]
I believe parse_datetime::parse_datetime::from_str supports parsing "@" syntax [in this section](https://github.com/uutils/parse_datetime/blob/main/src/parse_datetime.rs#L93-L100). Just added a new test to verify: https://github.com/uutils/parse_datetime/pull/31

**Comment by philolo1** [comment]
@Benjscho you are correct, i also added some tests (did not see your pr until now). #32
