### ISSUE TITLE
epoch parsing with timezone other than UTC

### ISSUE THREAD

**Issue by matrixhead** [uutils/parse_datetime#66]
hi, i think our epoch parsing is not working properly.

if we try to run [test_epoch_seconds](https://github.com/uutils/parse_datetime/blob/96d8c7c294161181921a3e2c1dfa895b6339c6f1/src/lib.rs#L316) it would work but if we try changing the timezone to something like `env::set_var("TZ", "EST")` it would fail. it shouldn't be doing that right? because epoch's should be same even if we change the timezone.

i think it is happening because we are treating `NaiveDateTime` returned by [from_timestamp_opt](https://github.com/uutils/parse_datetime/blob/96d8c7c294161181921a3e2c1dfa895b6339c6f1/src/lib.rs#L202C54-L202C72) (which is in UTC) as local time in [naive_dt_to_fixed_offset](https://github.com/uutils/parse_datetime/blob/96d8c7c294161181921a3e2c1dfa895b6339c6f1/src/lib.rs#L254C4-L254C28) and i think we could fix it by treating it as UTC

if you guys think i'm right can i put together a pr with the necessary changes

**Comment by tertsdiepraam** [comment]
If it's easy sure, otherwise we can defer this to the new parser.

**Comment by matrixhead** [comment]
it is a single line change i can put together a pr ASAP 😃, thanks
